限制修改badge
XMOJ-Script-dev/XMOJ-bbs pull request #15
Opened 2024-04-05 11:57 UTC by PythonSmall-Q

2024-04-05 13:56 UTC, boomzero requested changes

2024-04-05 13:56 UTC, boomzero commented on Source/Process.ts
> -      await sleep(500);
干什么...

2024-04-05 13:56 UTC, boomzero commented on Source/Process.ts
> +    let retryCount = 3; // Define how many times you want to retry
Why?

2024-04-05 13:56 UTC, boomzero commented on Source/Process.ts
> +          return new Result(false, "用户名必须为小写");
不要format...

2024-04-05 13:56 UTC, boomzero commented on Source/Process.ts
> +  private AllowEditList: Array<string> = ["zhuchenrui2", "shanwenxiao", "shihongxi"];
hmm... 我觉得可以`denyeditlist`

2024-04-05 14:05 UTC, boomzero commented
哇swx好棒! 终于干活了!!! @PythonSmall-Q

2024-04-05 14:13 UTC, boomzero requested changes

2024-04-05 14:13 UTC, boomzero commented on Source/Process.ts
> +      if (!this.IsAdmin() && !this.AllowEdit() && Data["UserID"] !== this.Username) {
@PythonSmall-Q ~你是学OI的吗??? 你逻辑运算符学过没有???~

2024-04-05 14:16 UTC, boomzero approved these changes

2024-04-05 14:17 UTC, merged

2024-04-05 14:19 UTC, boomzero commented
done!

2024-04-06 02:04 UTC, PythonSmall-Q commented
tks

2024-04-06 02:04 UTC, PythonSmall-Q commented
@boomzero 
![image](https://github.com/XMOJ-Script-dev/XMOJ-bbs/assets/106425289/d40bb509-4ac9-4846-8baa-8b4d1e454a73)
你tm干嘛呢