修改长度限制
XMOJ-Script-dev/XMOJ-bbs pull request #27
Opened 2024-07-09 12:41 UTC by PythonSmall-Q

2024-07-09 13:44 UTC, PythonSmall-Q commented
都在上课发代码

2024-07-09 13:45 UTC, PythonSmall-Q commented
@boomzero

2024-07-09 14:00 UTC, boomzero commented
不用管, ~而且不要翻数据库~

2024-07-09 14:00 UTC, boomzero commented
本来就是这样设计的...

2024-07-09 14:01 UTC, boomzero commented
发代码

2024-07-10 05:09 UTC, boomzero requested changes
see my comments

2024-07-15 12:44 UTC, closed without merging