陶片放逐
XMOJ-Script-dev/XMOJ-bbs pull request #8
Opened 2024-01-12 07:11 UTC by PythonSmall-Q

2024-01-12 07:12 UTC, PythonSmall-Q commented
@boomzero 你看一眼这个对吗orz

2024-01-12 07:14 UTC, PythonSmall-Q commented
所以tnnd数字是要加1吗？
我看站务版加一了

2024-01-12 07:36 UTC, langningchen commented
@PythonSmall-Q 思路挺新奇

2024-01-12 07:40 UTC, boomzero commented
> 所以tnnd数字是要加1吗？ 我看站务版加一了

yes

2024-01-12 07:41 UTC, boomzero requested changes
还要改 https://github.com/XMOJ-Script-dev/XMOJ-bbs/blob/master/migrations/0000_init.sql
其实不是改, 是用wrangler新建一个migration

2024-01-13 03:20 UTC, closed without merging

2024-01-13 03:26 UTC, boomzero commented
> 所以tnnd数字是要加1吗？ 我看站务版加一了

wtf `wrangler dev`下要加一
workers上不用

2024-01-13 08:44 UTC, langningchen commented
@boomzero 那是因为你本地的数据库和远程的不一样

2024-01-14 04:54 UTC, PythonSmall-Q commented
why close？？？？ @boomzero

2024-01-14 04:58 UTC, boomzero commented
@PythonSmall-Q https://github.com/XMOJ-Script-dev/XMOJ-bbs/commit/4f520dea4485c1e5041644474dae363c7d033be0

2024-01-14 05:02 UTC, PythonSmall-Q commented
Oopse没看到